# Copyright (c) 2016-2022 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Documentation
site_url: https://www.cellmobs.com/
site_author: Cellmobs, Inc.
site_description: >-
  Cellmobs is a scalable and flexible cross-platform framework for 
  building modern web and mobile applications. 
# Repository
repo_name: cellmobs/cellmobs-docs
repo_url: https://github.com/cellmobs/cellmobs.github.io

# Copyright
copyright: Copyright &copy; 2012 - 2023 Cellmobs, Inc.

# Configuration
theme:
  name: null
  custom_dir: !ENV [THEME_DIR, "material"]
  logo: assets/logo-dark.png

  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
    - announce.dismiss    
  palette:
    - scheme: cellmobs
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: ui-monospace,SFMono-Regular,SF Mono,Menlo,Consolas,Liberation Mono,monospace
  favicon:  assets/logo.png
  icon:
    logo: logo

# Plugins
plugins:
  - search
  - glightbox
  - redirects:
      redirect_maps:
  - minify:
      minify_html: true
# Customization
extra_css:
  - stylesheets/extra.css
extra:
  analytics:
    provider: google
    property: G-1DVDQDG3HR
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cellmobs
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/squidfunk/mkdocs-material/
    - icon: fontawesome/brands/jira
      link: https://cellmobs.atlassian.net/

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: https://dev.cellmobs.com
  - Getting started:
    - Introduction: getting-started.md
    - Create your first App: setup/creating-apps.md
    - React SDK : setup/react-sdk.md
    - Nuxt SDK : setup/nuxt-sdk.md
    - Customization: customization.md
    - Creating your site: setup/creating-a-website.md
    - Philosophy: philosophy.md
    - Technologies: technologies.md
    - Alternatives: alternatives.md
    - License: license.md
    - Changelog:
      - changelog/index.md
  - Configuration:  
    - Quickstart: setup/quickstart.md
    - Setup &amp Management: setup/setup-and-management.md
    - Global Settings: setup/global-settings.md
    - Your App Organization: setup/your-app-organization.md
    - Security: setup/security.md
    - Image Settings: setup/image-settings.md
    - Message Templates: setup/message-templates.md
    - Data Model &amp; Schema: setup/model-schema.md
    - Taxonomy: setup/taxonomy.md
    - Workflow: setup/setting-up-workflow.md
    - Integrations: setup/setting-up-integrations.md
    - Tags: setup/setting-up-tags.md
  - App Console:
    - Overview : app-console/console-overview.md
    - Content: app-console/manage-content.md
    - Data: app-console/manage-data.md
    - Integrations: app-console/manage-integrations.md
    - Logging In : app-console/console-login.md
    - Orders: app-console/manage-orders.md
    - Organizations: app-console/manage-organizations.md
    - Pages: app-console/manage-pages.md
    - Products: app-console/manage-products.md
    - Requirements: app-console/manage-requirements.md
    - Subscriptions: app-console/manage-subscriptions.md
    - Tags: app-console/manage-tags.md
    - Templates: app-console/manage-templates.md
    - Taxonomy: app-console/manage-taxonomy.md
    - Users: app-console/manage-users.md
    - Vocabularies: app-console/manage-vocabularies.md
    - Workflow: app-console/manage-workflow.md
    - Other Functionalities: app-console/other-settings.md
  - Development Guide :
    - Overview: guide/development-guide.md
    - Authentication: guide/authentication.md
    - Customer Management : guide/customer-management.md
    - Creating Web Pages : guide/creating-web-pages.md
    - E-Commerce : guide/e-commerce.md
    - Managing Files : guide/managing-files.md
    - Marketplaces : guide/marketplaces.md
    - Communities : guide/communities.md
    - Syndication : guide/syndication.md    
    - Aggregation : guide/aggregation.md    
    - SEO: guide/seo.md
  - Reference:
    - https://api.cellmobs.com
  - Your Apps:
    - https://dev.cellmobs.com/apps
